version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - poetry export --dev --without-hashes > requirements.txt
      - sed -i '/^torch$/d' requirements.txt

sphinx:
   configuration: docs/conf.py

python:
   install:
   - requirements: requirements.txt
