version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - python3 -m venv ~/poetry_home
      - ~/poetry_home/bin/pip install poetry==1.2.0
      - ~/poetry_home/bin/poetry export --extras demos --with=dev --without-hashes -o requirements.txt
      - sed -i "/^torch$/d" requirements.txt
      - echo "-e ." >> requirements.txt
      - echo "--extra-index-url https://download.pytorch.org/whl/nightly/cpu" >> requirements.txt
      - echo 'torch' >> requirements.txt

sphinx:
   configuration: docs/conf.py

python:
   install:
   - requirements: requirements.txt
